FROM node:16-alpine

USER node
RUN mkdir -p /home/node/app

WORKDIR '/home/node/app'

# --chown=root
COPY  --chown=node:node package.json .
RUN npm install

# --chown=vikin:vikin 
COPY  --chown=node:node . .

CMD [ "npm", "run", "start" ]