# Elastic Beanstalk
# Choose: 'Docker running on 64bit Amazon Linux 2'
# it uses by default a docker-compose.yml file instead of a Dockerfile

version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
